export const vi = {
  nav: {
    logo: "Plant Detec",
    signIn: "Đăng nhập",
    signUp: "Tạo tài khoản",
    signOut: "Đăng xuất",
    dashboard: "Trang chủ",
    history: "Lịch sử",
    diagnose: "Chẩn đoán",
  },
  auth: {
    signInTitle: "Đăng nhập tài khoản",
    signUpTitle: "Tạo tài khoản mới",
    email: "Email",
    emailPlaceholder: "email@example.com",
    password: "Mật khẩu",
    passwordPlaceholder: "Nhập mật khẩu",
    forgotPassword: "Quên mật khẩu?",
    noAccount: "Chưa có tài khoản?",
    haveAccount: "Đã có tài khoản?",
    signIn: "Đăng nhập",
    signUp: "Đăng ký",
    signInBtn: "Đăng nhập",
    signUpBtn: "Tạo tài khoản",
    signOutBtn: "Đăng xuất",
    showPassword: "Hiện mật khẩu",
    hidePassword: "Ẩn mật khẩu",
    errors: {
      invalidEmail: "Email không hợp lệ",
      weakPassword: "Mật khẩu tối thiểu 6 ký tự",
      wrongCredentials: "Email hoặc mật khẩu không đúng",
      emailTaken: "Email này đã được sử dụng",
      generic: "Đã xảy ra lỗi, vui lòng thử lại",
    },
  },
  upload: {
    title: "Tải ảnh lá cây lên",
    dragHint: "Kéo thả ảnh vào đây",
    uploadHint: "Kéo thả hoặc bấm để chọn ảnh lá cây",
    uploadSubHint: "hoặc bấm để chọn từ thiết bị",
    orText: "hoặc",
    browseBtn: "Chọn từ thiết bị",
    chooseFile: "Chọn file",
    cameraBtn: "Chụp ảnh",
    takePhoto: "Chụp ảnh",
    deleteImage: "Xóa ảnh đã chọn",
    sizeHint: "JPG, PNG, WEBP · Tối đa 10MB",
    errors: {
      wrongType: "Chỉ nhận ảnh JPG, PNG hoặc WEBP",
      invalidType: "Định dạng không hợp lệ. Chỉ hỗ trợ JPG, PNG hoặc WEBP.",
      tooLarge: "Ảnh quá lớn, tối đa 10MB",
      uploadFailed: "Tải ảnh thất bại, vui lòng thử lại",
    },
  },
  diagnosis: {
    title: "Chẩn đoán bệnh cây",
    uploadHint: "Kéo thả hoặc bấm để chọn ảnh lá cây",
    uploadSubHint: "hoặc bấm để chọn từ thiết bị",
    chooseFile: "Chọn file",
    takePhoto: "Chụp ảnh",
    deleteImage: "Xóa ảnh đã chọn",
    startBtn: "Bắt đầu chẩn đoán",
    analyzing: "Đang phân tích...",
    resultTitle: "Kết quả chẩn đoán",
    plant: "Loại cây",
    disease: "Bệnh phát hiện",
    confidence: "Độ tin cậy",
    plantConfidence: "Nhận diện cây",
    diseaseConfidence: "Nhận diện bệnh",
    recommendation: "Hướng điều trị",
    healthyRecommendation: "Cây trồng đang phát triển tốt. Tiếp tục chăm sóc như hiện tại.",
    noRecommendation: "Chưa có khuyến nghị phù hợp cho kết quả này.",
    invalidType: "Định dạng không hợp lệ. Chỉ hỗ trợ JPG, PNG hoặc WEBP.",
    tooLarge: "Ảnh quá lớn. Vui lòng chọn file tối đa 10MB.",
    steps: {
      uploading: "Đang tải ảnh lên...",
      analyzingPlant: "Đang nhận diện loại cây...",
      analyzingDisease: "Đang phân tích bệnh...",
      done: "Phân tích hoàn tất",
      error: "Đã xảy ra lỗi",
    },
    result: {
      title: "Kết quả chẩn đoán",
      plant: "Loại cây",
      disease: "Bệnh phát hiện",
      confidence: "Độ tin cậy",
      recommendation: "Hướng điều trị",
      healthy: "Cây khỏe mạnh",
      healthyDesc: "Không phát hiện dấu hiệu bệnh. Tiếp tục chăm sóc như hiện tại.",
    },
    severity: {
      healthy: "Khỏe mạnh",
      mild: "Bệnh nhẹ",
      severe: "Bệnh nặng",
      unknown: "Không xác định",
    },
    errors: {
      generic: "Chẩn đoán thất bại, vui lòng thử lại",
      noPlant: "Không nhận diện được loại cây trong ảnh",
      lowQuality: "Ảnh không đủ rõ, hãy chụp lại gần hơn",
      serverDown: "Dịch vụ đang bảo trì, vui lòng thử lại sau",
    },
  },
  severity: {
    healthy: "Khỏe mạnh",
    mild: "Có bệnh - Nhẹ",
    severe: "Có bệnh - Nghiêm trọng",
    unknown: "Không xác định",
  },
  feedback: {
    question: "Kết quả này có chính xác không?",
    correct: "Đúng rồi",
    incorrect: "Chưa đúng",
    selectCorrect: "Chọn kết quả đúng",
    submitBtn: "Gửi phản hồi",
    send: "Gửi phản hồi",
    cancelBtn: "Hủy",
    thanks: "Cảm ơn bạn! Phản hồi giúp AI tốt hơn.",
    plant: "Cây",
    disease: "Bệnh",
    saveError: "Không thể lưu phản hồi.",
  },
  dashboard: {
    greeting: "Xin chào",
    totalDiagnoses: "Tổng chẩn đoán",
    thisWeek: "Tuần này",
    mostCommonPlant: "Cây hay gặp nhất",
    accuracyRate: "Tỉ lệ phản hồi đúng",
    recentActivity: "Hoạt động gần đây",
    chartTitle: "Chẩn đoán 7 ngày qua",
    noDiagnoses: "Chưa có chẩn đoán nào",
    noDiagnosesHint: "Hãy tải ảnh lá cây đầu tiên của bạn",
    startBtn: "Chẩn đoán ngay",
    loadMore: "Tải thêm",
    noMore: "Đã hiển thị tất cả",
  },
  history: {
    title: "Lịch sử chẩn đoán",
    filterAll: "Tất cả",
    filterHealthy: "Khỏe mạnh",
    filterDiseased: "Có bệnh",
    searchPlaceholder: "Tìm theo cây hoặc bệnh...",
    empty: "Không tìm thấy kết quả",
    emptyHint: "Thử thay đổi bộ lọc",
  },
  common: {
    loading: "Đang tải...",
    error: "Đã xảy ra lỗi",
    retry: "Thử lại",
    cancel: "Hủy",
    save: "Lưu",
    delete: "Xóa",
    confirm: "Xác nhận",
    back: "Quay lại",
    next: "Tiếp tục",
    close: "Đóng",
  },
} as const;

export type Vi = typeof vi;
